declare const SQUIRREL_ENV: {
	CLIENT_ID: string;
	REDIRECT_URI: string;
	INVITE_PERMISSIONS: string;

	APP_NAME: string;
	APP_DESCRIPTION: string;
	APP_SOURCE_CODE: string;
	APP_LIBRARIES_LINK: string;
};

export const { CLIENT_ID, REDIRECT_URI, INVITE_PERMISSIONS, APP_NAME, APP_DESCRIPTION } = SQUIRREL_ENV;
